name: 'CICD for vegitables'

on:
  push:
    branches: [ "vegitables" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      metrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: ${{metrix.node-version}}
      - name: build
        run: |
          docker-compose up --build
        env:
          CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
      - name: connect to SSH
      - uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.HOST}}     
            username: ${{secrets.USER}}     
            key: ${{secrets.KEY}}     
            port: ${{secrets.PORT}}  
            script: |
                npm install -g pm2
                docker stop $(docker ps -a -q)
                docker rm $(docker ps -a -q)
                cd -/A-Tech-Solution-angular
                git pull origin vegitables
                docker-compose up --build  
